# Copyright (c) 2022 Jason F. Macas(@Hikki12) <franciscomacas3@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


site_name: REMIO


site_url: https://hikki12.github.io/remio/
site_author: Jason F. Macas

# Repository
repo_name: Hikki12/remio
repo_url: https://github.com/Hikki12/remio
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 Jason F. Macas(@Hikki12)

theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: youtube
      primary: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Amiko

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
